version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - '3005:80'
    volumes:
      - './.nginx:/etc/nginx/conf.d'
      - ./laravel:/var/www/laravel
    depends_on:
      - app

  db:
    image: mysql:8.0.35
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
